# Generated by Django 4.2.11 on 2024-11-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Role_Management", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
